name: Build ZLD Audio Control

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ZLDAudioControl.csproj

      - name: Build
        run: dotnet build ZLDAudioControl.csproj -c Release --no-restore

      - name: Publish
        run: |
          dotnet publish ZLDAudioControl.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -o publish

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ZLD-Audio-Control
          path: publish
